services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./app:/app
    ports:
      - "${PORT_NODE:-3000}:3000"
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
